id: 'DVAE_64'
model: DVAE
beta: 1
model_params:
  class_latent_size: 16
  content_latent_size: 64
training:
  data_root: './64_frames' # './data/128_frames/train'
  eval_root: './64_frames_test' # './data/128_frames/eval'
  epoch: 200
  num_workers: 4
  batch_size: 24
  lr: 0.0001
  corruptions: ['frost', 'fog']
  intensities: [5,5]
  save_freq: 10
eval:
  path: ./checkpoints/DVAE/weather/best_model.pt
  root: './data/128_frames/eval'
  # corruptions: ['frost', 'fog']
  # intensities: [5,5]
  corruptions: ['frost', 'fog', 'gaussianBlur', 'speckleNoise', 'impulseNoise']
  intensities: [5,5,1,1,1]