id: 'Celeb_a'
model: VAE
beta: 1
model_params:
  class_latent_size: 16
  content_latent_size: 64
training:
  data_root: './data/128_frames/train'
  eval_root: './data/128_frames/eval'
  epoch: 200
  num_workers: 4
  batch_size: 2
  lr: 0.0001
  corruptions: ['frost', 'fog']
  intensities: [5,5]
  save_freq: 10
eval:
  path: ./checkpoints/VAE/weather/best_model.pt
  root: './data/128_frames/eval'
  corruptions: ['frost', 'fog', 'gaussianBlur', 'speckleNoise', 'impulseNoise']
  intensities: [5,5,1,1,1]
  # corruptions: ['gaussianBlur', 'speckleNoise', 'impulseNoise']
  # intensities: [1,1,1]